### ISSUE TITLE
Intellisense not showing colour preview swatches

### ISSUE THREAD

**Issue by mjbates7** [bradlc/vscode-tailwindcss#113]
Hello,

Is there any reason why I wouldn't be seeing the colour preview swatches in the intellisense that pops up? I have all the class names available, but the colour swatches aren't appearing?

![image](https://user-images.githubusercontent.com/4522738/80797126-e61a6200-8b98-11ea-9bde-9bbd9b651d44.png)

Transparent is the only one showing.
![image](https://user-images.githubusercontent.com/4522738/80797339-83759600-8b99-11ea-9fd9-4870af244b8b.png)

**version info**
tailwind 1.4.0
extension 0.2.0

**vscode:**
Version: 1.45.0-insider (user setup)
Date: 2020-05-01T05:22:54.431Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

I've reinstalled the plugin too and restarted vscode.

Many thanks

**Comment by bradlc** [comment]
Hey @mjbates7. This is because of the new [opacity modifiers in Tailwind 1.4](https://github.com/tailwindcss/tailwindcss/pull/1627):

```css
/*  Before */
.bg-red-500 {
  background-color: #f56565
}

/* Now */
.bg-red-500 {
  --bg-opacity: 1;
  background-color: #f56565;
  background-color: rgba(245, 101, 101, var(--bg-opacity));
}
```

Currently the logic for plucking the color out of the styles is _roughly_ "is there a single CSS property and is the value a color?"

I'm in the process of improving the logic which will fix this. I'll hopefully release a new alpha version this weekend with this included.
